[fix] rollback to commit e5dcc97c6fc4d8c0f4ee5b63286d341fb673ff79

diff --git a/.github/workflows/virtuoso.yml b/.github/workflows/virtuoso.yml
--- a/.github/workflows/virtuoso.yml
+++ b/.github/workflows/virtuoso.yml
@@ -8,11 +8,6 @@ on:
     branches-ignore:
       - "main"
 
-env:
-  HOST : localhost
-  PORT : 8890
-  VIRTUOSO_SERVER_URL: http://localhost:8890/sparql
-
 jobs:
   setup:
     runs-on: ubuntu-latest
@@ -29,19 +24,8 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      # - name: Setup Go
-      #   uses: actions/setup-go@v2
-      #   with:
-      #     go-version: 1.21
-
-      # - name: Sleep seconds
-      #   run: sleep 15
-
-      - name: Wait for virtuoso to start
-        run: |
-          wget -q https://github.com/vishnubob/wait-for-it/raw/master/wait-for-it.sh
-          chmod +x wait-for-it.sh
-          ./wait-for-it.sh localhost:8890 -t 15
+      - name: Sleep seconds
+        run: sleep 15
 
       - name: Show /etc/hosts
         run: cat /etc/hosts
@@ -56,6 +40,15 @@ jobs:
           echo "::set-output name=response::$OUTPUT"
         shell: bash
 
-
-      # - name: Run Go Tests
-      #   run: go test ./...
+      - name: Check response
+        id: check_response
+        run: |
+          OUTPUT="${{ steps.test_virtuoso.outputs.response }}"
+          if [[ $OUTPUT == *"results"* ]]; then
+            echo "Server is running and responded correctly"
+          else
+            echo $OUTPUT
+            echo "Server is not responding or there was an error in the response"
+            exit 1
+          fi
+        shell: bash
